
language: swift
osx_image: xcode12.4
before_install:
    - swift package update
    - swift package generate-xcodeproj
env:
    global:
        - PGPORT=5433
before_script:
    - sudo service postgresql start
    - psql -c 'create database vapor_base_test;' -U adamzarn
script:
    - xcodebuild -project vapor-base.xcodeproj -scheme vapor-base-Package -destination 'platform=OS X' clean test
after_success:
    - bash <(curl -s https://codecov.io/bash) -t {CODECOV_TOKEN}
