addons:
    postgresql: "13.2"
env:
    global:
        - PGPORT=5433
language: swift
osx_image: xcode12.4
before_install:
    - swift package update
    - swift package generate-xcodeproj
install:
    - export PG_DATA=$(brew --prefix)/var/postgres
    - pg_ctl -w start -l postgres.log --pgdata ${PG_DATA}
    - createuser -s postgres
    - psql -c 'create database vapor_base_test;' -U postgres
    - cat postgres.log
script:
    - xcodebuild -project vapor-base.xcodeproj -scheme vapor-base-Package -destination 'platform=OS X' clean test
after_success:
    - bash <(curl -s https://codecov.io/bash) -t {CODECOV_TOKEN}
