#!/bin/bash

CODECOV_TOKEN=$1

swift test --enable-code-coverage
xcrun llvm-cov export -format="lcov" -instr-profile=$(find .build -name default.profdata) $(find .build -name vapor-basePackageTests) > info.lcov
bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN