#!/bin/bash

if [[ $# -eq 0 ]] ; then
    echo 'You must provide a CODECOV_TOKEN'
    exit 0
fi

SCRIPTS_DIRECTORY=`dirname "$0"`
ROOT_DIRECTORY=$SCRIPTS_DIRECTORY/..

cd $ROOT_DIRECTORY

CODECOV_TOKEN=$1

swift test --enable-code-coverage
xcrun llvm-cov export -format="lcov" -instr-profile=$(find .build -name default.profdata) $(find .build -name vapor-basePackageTests) > info.lcov
bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN