#!/bin/bash

if [[ $# -eq 0 ]] ; then
    echo 'You must provide a CODECOV_TOKEN'
    exit 0
fi

SCRIPTS_DIRECTORY=`dirname "$0"`
ROOT_DIRECTORY=$SCRIPTS_DIRECTORY/..

cd $ROOT_DIRECTORY

CODECOV_TOKEN=$1

xcrun llvm-cov export -format="lcov" -instr-profile=$(find .build -name default.profdata) $(find .build -name vapor-basePackageTests) > info.lcov

curl -Os https://uploader.codecov.io/latest/macos/codecov
chmod +x codecov
./codecov -t $CODECOV_TOKEN